### ISSUE TITLE
question: why did you change from unpkg to jsdelivr?

### ISSUE THREAD

**Issue by jthegedus** [jhildenbiddle/docsify-themeable#12]
Just curious

**Comment by jhildenbiddle** [comment]
Hi @jthegedus.

I made the switch after an unpkg bug broke redirect URLs (see https://github.com/unpkg/unpkg.com/issues/156). Bugs happen, but this particular one took a long time to fix and was very hard to verify that the fix worked for everyone. As I mentioned in the linked issue:

> Moving forward, I have decided to change the CDN links listed in my packages from unpkg.com to jsdelivr.com as a result of these redirect issues. As much as I appreciate unpkg.com and the unique "automated CDN from NPM" offering it pioneered, jsDelivr offers similar automated CDN services for npm packages along with additional features like support for GitHub repos, package statistics, automatic bundling and minification, and subresource integrity checks.

The only hiccup I've experienced is that jsDelivr content is cached longer on both the server and the client, so getting the latest version immediately after release requires extra fiddling or patience. I mentioned this in a jsDelivr issue (https://github.com/jsdelivr/jsdelivr/issues/18124) to which I received this helpful response from @MartinKolarik:

> The approach taken by unpkg almost completely eliminates client side caching because your browser makes a request for each file every minute. If there wasn't a new version, the file content isn't transferred again, but there's still the cost of making all those requests, and it can have a significant impact on the performance of your website.

Makes sense, so I now do the following:

- I use unpkg when I am using a version redirect URL (e.g. `@latest`, `@1`, `@1.2`) in development to ensure I'm getting the very latest version.
- I use jsdelivr when I am using a version redirect URL in production or specifying a version (e.g. `@1.2.3`)

Seems to be working well so far. 😄

**Comment by jthegedus** [comment]
Very useful information. Thanks again for taking the time to formulate such a useful answer :smile: It'd probably be useful to have a comparison in Docsify.

**Comment by jhildenbiddle** [comment]
You bet. Happy to help.

FWIW, I've filed an issue (https://github.com/docsifyjs/docsify/issues/756) suggesting the maintainers consider making the same switch. It's easy enough for folks to choose jsDelivr over unpkg on their own *if* they are aware of it, but I suspect many docsify users blindly copy-paste the links provided in the docs.

**Comment by jthegedus** [comment]
Your are 100% correct. I'm aware of unpkg, but was not aware of the differences between CDNs so blindly used unpkg. I think recommending unpkg during development and jsdelivr for prod stability is the way to go.
