### ISSUE TITLE
No way to change the colour of the font inside the body of the search results

### ISSUE THREAD

**Issue by hlb8122** [jhildenbiddle/docsify-themeable#16]
While you can customize the header font color of the search result, there seems to be no option to customize the actual body font color of the search result?

https://jhildenbiddle.github.io/docsify-themeable/#/customization?id=search

Many thanks, and great work!

**Comment by jhildenbiddle** [comment]
Hey @hlb8122.

Apologies for the slow response. The last few weeks have been a little hectic.

I've added two new theme properties in 0.7.0: 

* `--search-result-item-color`
* `--search-result-item-weight`

Enjoy, and thanks for the kind words. :)
