### ISSUE TITLE
emoji not working

### ISSUE THREAD

**Issue by LDNN97** [jhildenbiddle/docsify-themeable#17]
<img width="741" alt="image" src="https://user-images.githubusercontent.com/12992623/52683677-88432f80-2f7e-11e9-99e9-591b8de900bf.png">

**Comment by jhildenbiddle** [comment]
Thanks for the heads up, @LDNN97.

This is a docsify issue, so I have [filed an issue](https://github.com/docsifyjs/docsify/issues/768) in that repo.

Note to future self: consider auto-generating markdown demo from official unicode list: https://unicode.org/emoji/charts/index.html

**Comment by jhildenbiddle** [comment]
This has been fixed in the latest docsify release (4.9.1).
