### ISSUE TITLE
search not working

### ISSUE THREAD

**Issue by jrappen** [jhildenbiddle/docsify-themeable#18]
Search didn't work for me. Reverting commit linked below:

jrappen/sublime-wkhtmltopdf@9fcc5b1

Any suggestions?

**Comment by jhildenbiddle** [comment]
Hi @jrappen.

Based on what I see at https://jrappen.github.io/sublime-wkhtmltopdf/ I assume "didn't work for me" means the search box is visible but no results are returned. Yes?

If this is the case, the explanation is that docsify's search plugin is designed to return search results for multi-page sites only. I assume the logic behind that decision is that if all site data is contained on the page the user is looking at, the browser's built-in page search can be used instead via CMD/CTRL+F.

If you would like the search plugin to work on single-page sites consider creating a [docsify issue](https://github.com/docsifyjs/docsify/issues).

Thanks!

**Comment by jrappen** [comment]
Interesting, it used to work (even across translations).

For example a search for "installation" would return both matches, one each from the German and English translation.

**Comment by jrappen** [comment]
thanks for the input

**Comment by jhildenbiddle** [comment]
That is interesting. I didn't realize it worked in the past.

After doing a little more digging, it looks like single-page search functionality was broken in the 4.8.0 release. The easiest way to verify:

1. Load a single-page docsify site with docsify v4.8 or above
2. Notice the absence of `docsify.search` keys in the browser's local storage
3. Load the same single-page docsify site with docsify v4.7.x
4. Notice the `docsify.search.expires` and `docsify.search.index` entries have been added to the browser's local storage.

**Comment by timaschew** [comment]
I guess this is the reason: https://github.com/docsifyjs/docsify/pull/706

Another reason to add tests and merge new features and changes only with tests.
