### ISSUE TITLE
Unstyled scrollbar on long sidebar

### ISSUE THREAD

**Issue by phenomen** [jhildenbiddle/docsify-themeable#20]
I have pretty long sidebar and with default Docsify CSS there is no unstyled scrollbar but with Docsify-Themeable it appear there:

![chrome_m71m2eagdw](https://user-images.githubusercontent.com/138311/53295586-45762880-37c4-11e9-88a3-7682323b4a77.png)

**Comment by phenomen** [comment]
Here is how it looks with default Docsify dark theme (and some minor custom tweaks):

![chrome_ngjqqmwgve](https://user-images.githubusercontent.com/138311/53299681-0ca97400-3803-11e9-8389-a7842b99a44b.png)

**Comment by jhildenbiddle** [comment]
Hi @Phenomen,

May I ask what OS and browser you are using so I can verify a fix?

**Comment by phenomen** [comment]
- Windows 10
- Google Chrome 72.0.3626.119

**Comment by jhildenbiddle** [comment]
Fixed in 0.7.1.

Scrollbar styles have been adjusted in Mozilla (Firefox) as well as Webkit-based browsers on non-macOS platforms.

Note that it can take up to 12 hours for the CDN cache to update and up to 7 days for local files to expire due to cache headers. You can always override this by specifying the version number in the URL, but I wouldn't recommend this as it means you won't automatically receive minor and patch updates. Long story short: check your site around 10am tomorrow, and do a hard-refresh on the browser if necessary.

**Comment by pShota** [comment]
I have the same problem, any idea?

<img width="538" alt="Screenshot 2021-08-18 at 10 39 51 PM" src="https://user-images.githubusercontent.com/1772621/129918535-2585efdf-958a-4dd3-8fdf-a616ec806dd3.png">

**Comment by jhildenbiddle** [comment]
Hi @pShota --

I can see the scrollbar in your screenshot so I don't doubt this is happening, but I am unable to reproduce this issue on any of the following browsers:

- Chrome (macOS & Windows 10)

  <img width="1392" alt="chrome-mac" src="https://user-images.githubusercontent.com/442527/131748696-82e8493f-3ab1-4f00-a2fc-76beb3b7971e.png">
  <img width="1280" alt="chrome-win" src="https://user-images.githubusercontent.com/442527/131748723-044976ae-5e7a-4fef-9730-442c308757e9.png">

- Edge (Windows)

  <img width="1280" alt="edge-win" src="https://user-images.githubusercontent.com/442527/131748819-c47d0327-579c-48e0-b240-6903813a0fce.png">

- Firefox (macOS & Windows 10)

  <img width="1392" alt="firefox-mac" src="https://user-images.githubusercontent.com/442527/131748840-a85f8c07-46a1-4b3c-ab42-c71b5e83711a.png">
  <img width="1280" alt="firefox-win" src="https://user-images.githubusercontent.com/442527/131748918-c02f81d1-c045-4aaf-ad6e-24a0ff894533.png">

- Safari (macOS)

  <img width="1392" alt="safari-mac" src="https://user-images.githubusercontent.com/442527/131748954-7a6e73a1-c763-45ea-baa8-44aa2277a546.png">

I wish I could provide more valuable feedback, but there isn't much I can do if I can't reliably reproduce the issue. Perhaps you can try different browsers to determine if this is an OS-level scrollbar issue (likely happening in multiple browsers) or an issue with a particular browser.

**Comment by pShota** [comment]
> I wish I could provide more valuable feedback, but there isn't much I can do if I can't reliably reproduce the issue. Perhaps you can try different browsers to determine if this is an OS-level scrollbar issue (likely happening in multiple browsers) or an issue with a particular browser.

@jhildenbiddle Thanks for the response.
hmm, I just load the [github page](https://jhildenbiddle.github.io/docsify-themeable/#/introduction) again and found no issue.
I should mention it happened only in dark theme and I used Chrome and Brave browser.

But if anyone encounter the same issue I recommend the followings:
use css in your page to override the scrollbar color

```css
/* scrollbar color */
::-webkit-scrollbar {
    background: #262e32;
    width: 4px;
}
::-webkit-scrollbar-thumb {
    background: #888;
}
```
