### ISSUE TITLE
Lens' icon not showing correctly on Firefox

### ISSUE THREAD

**Issue by acataluddi** [jhildenbiddle/docsify-themeable#21]
Hi John,
thank you for your great theme. It seems that the lens icon is not showing correctly on Firefox (release details below).

![PrtScr capture](https://user-images.githubusercontent.com/8874358/54745673-60249d00-4bca-11e9-9540-6fc22aa506f4.png)

You can also check the issue using this fork:
https://codesandbox.io/s/zn28zm0nkm

Kind regards,
Adriano

## Runtime Configuration 
**Browser**: Mozilla Firefox 66.0 x64
**OS**: Microsoft Windows 8.1 Professional x64

**Comment by jhildenbiddle** [comment]
Hi @acataluddi.

I'm not seeing this issue on Firefox 65 or 66 on Mac or Windows.

**Mac**

![mac](https://user-images.githubusercontent.com/442527/54784322-cb796980-4be0-11e9-846c-51df004ef3bb.png)

**Windows**

![windows](https://user-images.githubusercontent.com/442527/54784324-cfa58700-4be0-11e9-99a3-1a841207990f.png)

Any chance you have a browser extension running that is causing the issue? If not, try visiting the in a private window (Ctrl+Shift+P) and visiting https://jhildenbiddle.github.io/docsify-themeable/ to see if it's a cache issue.

**Comment by acataluddi** [comment]
Hi @jhildenbiddle,

thank you for your quick reply. I've just tried using Firefox in a private session and the result is quite bizarre. There is still a rendering issue but now looks differently:

![PrtScr capture](https://user-images.githubusercontent.com/8874358/54876964-ba1aa200-4e18-11e9-8d03-55e880e8216e.png)

Regards,
Adriano C.

**Comment by acataluddi** [comment]
@jhildenbiddle,

I've just started Firefox in "safe mode" by running:

```bash
firefox.exe -safe-mode
```

Interestingly the lens icon is now rendered correctly. 

![immagine](https://user-images.githubusercontent.com/8874358/54877032-ac195100-4e19-11e9-82d0-73e7ff33453d.png)

I suspect I have some local problem to solve. I'll do further test and update this issue to hopefully help someone else who might have the same problem in future.

**Comment by acataluddi** [comment]
Hi @jhildenbiddle,  

I think I've found the problem. The root cause seems to be the Hardware Acceleration (here is [how to turn off in Firefox](https://support.mozilla.org/en-US/kb/troubleshoot-extensions-themes-to-fix-problems#w_turn-off-hardware-acceleration))

![2017-08-27-03-46-52-fd0019](https://user-images.githubusercontent.com/8874358/54878730-05d94580-4e31-11e9-97c6-10143104229d.png)

I think I need to update my GPU drivers and see if the problem goes away as running without hardware acceleration is a suboptimal solution.

Thank you for you time and sorry for the hassle.

Best regards,
Adriano

**Comment by jhildenbiddle** [comment]
Thanks for following up, @acataluddi.

Very strange. It could also be a bug in Firefox, especially if you aren't seeing the same issue with hardware acceleration enabled in other browsers like Chrome.

Regardless, good luck getting it figured out and thanks for taking the time to create the issue. Much appreciated.
