### ISSUE TITLE
Emoji is killing datetime

### ISSUE THREAD

**Issue by VagnerDomingues** [jhildenbiddle/docsify-themeable#23]
![emoji :01: ](https://user-images.githubusercontent.com/5666881/56824178-1f085400-682c-11e9-8510-749713a993e3.png)

emoji :01: is breaking formatted datetime :cry:  i couldn't find an option to ignore them on themeable plugin

**Comment by jhildenbiddle** [comment]
Hi @VagnerDomingues.

This is a [docsify issue](https://github.com/docsifyjs/docsify/issues), not docsify-themeable. If you create an issue in the docsify repo we can triage the issue.

Thanks!
