### ISSUE TITLE
How do I change color of the sidebar 'arrow'?

### ISSUE THREAD

**Issue by filipgoc** [jhildenbiddle/docsify-themeable#25]
Hi!

I'm loving themeable. 

I changed the hue, but this element stays blue when active: 

![image](https://user-images.githubusercontent.com/16858474/58892631-dbd4b700-86ee-11e9-95e5-12cb5b7e3d9a.png)

I poured over the variables in 
https://cdn.jsdelivr.net/npm/docsify-themeable@0/src/scss/themes/defaults/_sidebar.css
and also
https://cdn.jsdelivr.net/npm/docsify-themeable@0/src/scss/themes/defaults/_content.css
https://cdn.jsdelivr.net/npm/docsify-themeable@0/src/scss/themes/defaults/_app.css
https://cdn.jsdelivr.net/npm/docsify-themeable@0/src/scss/themes/defaults/_base.css

and I just can't figure it out. 

Thanks!

**Comment by filipgoc** [comment]
One month anniversary. Anyone home @jhildenbiddle ? 

PS: Still loving your work on this.

**Comment by Teddy95** [comment]
Hey :)

[Change color of navbar arrows](https://github.com/jhildenbiddle/docsify-themeable/issues/3)

**Comment by jhildenbiddle** [comment]
@filipgoc --

See link provided by @Teddy95.

**Comment by jhildenbiddle** [comment]
Fixed in v0.9.0
