### ISSUE TITLE
How should I use markdown table native format

### ISSUE THREAD

**Issue by Han-YLun** [jhildenbiddle/docsify-themeable#36]
docsify-themeable:
![image](https://user-images.githubusercontent.com/44769070/70400778-885d7000-1a67-11ea-8be7-ea53096c205e.png)

Native:
![image](https://user-images.githubusercontent.com/44769070/70400786-990de600-1a67-11ea-8482-fc514a0629b0.png)

I think native is better. How do I use the native markdown table format while using your theme?

**Comment by jhildenbiddle** [comment]
Hi @Han-YLun,

Check out the [Customization](https://jhildenbiddle.github.io/docsify-themeable/#/customization) section of the docs. You can easily modify table styles using the `--table` theme properties.

For example, customizing the following properties will set the borders, background colors, and padding to more closely match docsify's default style:

```html
<style>
  :root {
    /* Tables */
    --table-cell-border-width: 1px;
    --table-cell-padding: 0.5em 0.5em;
    --table-head-border-width: 1px;
    --table-row-even-background: var(--mono-tint3);
    --table-row-odd-background: inherit;
  }
</style>
```
