### ISSUE TITLE
can not see image after zoom with zoom image plugin

### ISSUE THREAD

**Issue by degbug** [jhildenbiddle/docsify-themeable#37]
before zoom:
![image](https://user-images.githubusercontent.com/11486075/72784669-4c234f00-3c64-11ea-9fb2-5ba289a75550.png)
after zoom:
![image](https://user-images.githubusercontent.com/11486075/72784699-5e9d8880-3c64-11ea-806f-4bbf866516a5.png)

**Comment by degbug** [comment]
I change the img css to set z-index to 999 to fix it。
I am not good at web, maybe can more elegant

**Comment by pdrastil** [comment]
+1 for this issue. Base on the investigation I could do the css class `.medium-zoom-image--opened` doesn't contain value for z-index from [_variales.scss](https://github.com/jhildenbiddle/docsify-themeable/blob/master/src/scss/app/_variables.scss) which should be 50.

**Comment by jhildenbiddle** [comment]
A change made in docsify 4.10 is the cause of the issue. This is confirmed by loading an earlier version of the plugin:

```html
<script src="https://unpkg.com/docsify@4.9/lib/plugins/zoom-image.min.js"></script>
```

Easy enough to fix.

**Comment by ChrysSills99** [comment]
Are you using simple.css theme?

There is a bug in the file:  :root{--zoomimage-overlay-background: rgba(0, 0, 0, 0.875)}

I had to override this in your index.html and set zoomimage-overlay-background: none and mine is working like a charm

**Comment by jhildenbiddle** [comment]
The issue was caused by a class name change in 4.10. 

In docsify < 4.10, the class name applied to the zoomed image was "medium-zoom-image--open". In 4.10, this changed to "medium-zoom-image--opened" (noted the "ed" added to "open").

This issue has been fixed and will be available in the upcoming release.
