### ISSUE TITLE
Ability to apply themeable visual styles to embedded HTML?

### ISSUE THREAD

**Issue by paulhibbitts** [jhildenbiddle/docsify-themeable#39]
Hello!

I am a pretty recent newbie user to both Docsify and Themeable, but I am finding the combination amazing - thanks for this great plugin! So much so that I've created a little Starter Kit for others: https://github.com/hibbitts-design/docsify-open-publishing-starter-kit

I have a page with an HTML button, and was wondering if there was a way to apply a themeable visual style (such as button color) to the button in a form? Here is a snippet of my HTML:

```
<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="submit" value="Contribute to this Project" name="submit1" alt="PayPal - The safer, easier way to pay online!" class="button">
</form>
```

I'd also love to be able to style a Markdown link as a button if possible.

Thanks very much,
Paul

**Comment by jhildenbiddle** [comment]
Hi @paulhibbitts.

The easiest way to accomplish this is by adding a custom stylesheet via a `<style>` or `<link rel="stylesheet">` tag to your `index.html` file. You can use any of the [theme properties](https://jhildenbiddle.github.io/docsify-themeable/#/customization?id=theme-styles) listed in the [docs](https://jhildenbiddle.github.io/docsify-themeable/) in your custom CSS:

```html
<style>
  .markdown-section .button {
    background-color: var(--theme-color);
  }
</style>
```

Adding styles via `<style>` and/or `<link rel="stylesheet">` tag(s) allows custom properties to work in legacy browsers (via the included [ponyfill](https://github.com/jhildenbiddle/css-vars-ponyfill)). If you don't care about legacy browsers, you can instead apply styles directly on elements via the `style` attribute:

```html
<input type="submit" value="Contribute to this Project" name="submit1" alt="PayPal - The safer, easier way to pay online!" style="background-color: var(--theme-color);">
```

Hope this helps.

**Comment by paulhibbitts** [comment]
That's amazing @jhildenbiddle , thank you so much - I've got it going already🙂
