### ISSUE TITLE
Updates for Docsify 5

### ISSUE THREAD

**Issue by trusktr** [jhildenbiddle/docsify-themeable#42]
Hello! I haven't tried this with the latest Docsify yet. I'm curious to know if everything works fine with the latest Docsify. If not, it'd be great to get things back in sync.

We've been chatting about Docsify maintenance and future work at https://gitter.im/docsifyjs/reviewers. Would you like to join us there? EDIT: Oh way, it is a private channel I think. @anikethsaha is managing that.

**Comment by anikethsaha** [comment]
added @jhildenbiddle  👍

**Comment by jhildenbiddle** [comment]
docsify-themeable works with the latest 4.x version of docsify, but I have not tried it with the unreleased, in-progress v5.

I've joined the Gitter channel you linked to. Happy to discuss the road to v5 there. Thanks for the heads up!
