### ISSUE TITLE
idea: choose theme in Customization page and see variable value for selected theme

### ISSUE THREAD

**Issue by trusktr** [jhildenbiddle/docsify-themeable#45]
I thought I'd write this random idea. Not sure if it is worth it, but might help people know what they want to override.

---

What would be neat is perhaps a select/dropdown to choose which theme to view the values for, and the page would update to show those values.

What would be a clean way to do this?

Maybe we could

- place the `<select>` HTML at the top of the markdown along with a `<script>` tag to make it interactive (or make it a Vue component or Custom Element).
- We could duplicate the list of CSS variables, once per theme, and wrap each one with a `<div>` with a `display: none` style.
- the `<select>` would control which `<div>` has a `.visible` class on it to set it back to `display: block`.

Or something along those lines. I like that the markdown is effectively the same as plain HTML, so we can stick any code in them.

I'm not sure if Docsify handles Vue component cleanup on page switches, but if we use custom elements then that isn't an issue as we can clean up anything in `disconnectedCallback`.

**Comment by jhildenbiddle** [comment]
It's an interesting idea. What about just linking to the source CSS (actually, SCSS) for the themes so people can access them easily from the docs? For example, if you wanted to see the properties for the "Simple" theme, it would be everything currently listed in the docs (the "default" values) with the following overrides:

https://unpkg.com/browse/docsify-themeable@0.8.1/src/scss/themes/theme-simple.scss

**Comment by trusktr** [comment]
I think that would be great. Also simpler to do. :)

**Comment by jhildenbiddle** [comment]
Sounds good. Re-opening as a reminder to myself. :)

**Comment by jhildenbiddle** [comment]
Links to the source are available both on the "Themes" and "Customization > Theme Styles" pages.
