### ISSUE TITLE
How can we make sidebar padding scale well with the search bar?

### ISSUE THREAD

**Issue by trusktr** [jhildenbiddle/docsify-themeable#48]
The default is `0 25px` but if you start to increase the number, the search bar starts not to fit.

For example, inspect the `.sidebar ` element, and add this style:

```css
--sidebar-padding: 0 25px;
```

then start to increase 25 to higher numbers.

![sidebar-padding](https://user-images.githubusercontent.com/297678/82126476-e8b4b400-9761-11ea-8065-4ad35cc56915.gif)

I think we also need to map the sidebar padding size as well as sidebar height to the negative margin of the search bar. Currently only the size is mapped.

**Comment by trusktr** [comment]
I'm currently trying to achieve the following while staying as much within the constraints of docsify-themeable:

![goal](https://user-images.githubusercontent.com/297678/82126565-785a6280-9762-11ea-806e-c3bc8c5f8626.png)

Once I'm done, I can share what were the occasions I had to step out of the constraints with custom CSS, then that may help to improve the docsify-themeable features.

**Comment by trusktr** [comment]
Maybe we want variables for both left and right sidebar padding?

What I'd like to do is have the text be padded away from the edges of the sidebar an arbitrary amount, but still have the blue highlight on the right side on the edge of the sidebar regardless of the padding size.

**Comment by jhildenbiddle** [comment]
There are several theme properties you can modify to accomplish the layout above, but I'd start with `--sidebar-nav-margin` and/or `--sidebar-nav-padding`. These are applied using standard `margin` and `padding` properties, so you can use 1/2/3/4 value shorthand notation to specify top/right/bottom/left.

Here's some sample CSS to get you started. This will look terrible, but it will help visualize how changing the values will affect the layout.

```css
:root {
  --sidebar-nav-background: red;
  --sidebar-nav-margin: 1.5rem 0 0 100px;
  --sidebar-nav-padding: 0 0 0 100px;
}
```
