### ISSUE TITLE
Images in a table disappear when resizing window to smartphone size.

### ISSUE THREAD

**Issue by sylwekb** [jhildenbiddle/docsify-themeable#5]
I have images in a table. When I preview the site in a smaller window, the pictures disappear. Do you have any idea what is going on? Is this a bug?

Normal size:
![normal-size](https://user-images.githubusercontent.com/2721405/46608974-b1ead680-cb06-11e8-8d91-ee0c020f64e9.png)

Mobile size:
![mobile-size](https://user-images.githubusercontent.com/2721405/46608973-b1ead680-cb06-11e8-89ea-e19b8209f95c.png)

Table looks like this:

```markdown
![nassau lamp](nassau-lamp.jpg)  | ![nassau lamp](nassau-lamp.png) | ![nassau lamp](nassau-lamp.webp)  | ![nassau lamp](nassau-lamp.bmp)
:-------------------------:|:-------------------------:|:-------------------------:|:-------------------------:
`nassau-lamp.jpg` *465 KB*  |   `nassau-lamp.png` *2.9 MB*   | `nassau-lamp.webp` *122 KB* |  `nassau-lamp.bmp` *7.6 MB*```

**Comment by jhildenbiddle** [comment]
It's not a bug per se, but it is an unintentional side effect of the responsive tables features that is enabled by default. 

The short explanation is that I hadn't accounted for images in the table header. The assumption was that table headers would contain text. You can see the intended affect by viewing [this page](https://jhildenbiddle.github.io/docsify-themeable/#/markdown?id=tables) with a mobile-sized viewport.

Fortunately there is an easy solution: just disable [`options.responsibeTables`](https://jhildenbiddle.github.io/docsify-themeable/#/options?id=responsivetables):

```javascript
window.$docsify = {
  // ...
  themeable: {
    responsiveTables: false
  }
}
```

**Comment by sylwekb** [comment]
Thanks! I'm using this as a workaround - but it's not that bad
