### ISSUE TITLE
 style for sidebar non <a href> elements

### ISSUE THREAD

**Issue by ajmedeiros** [jhildenbiddle/docsify-themeable#53]
Hi! First of all, thanks a lot for the great theme.
I'm not very experienced on web development and my english isn't the best, so I apologise if my question is hard to read.
I tried my best to make it work, but after some long hours I gave up :crying_cat_face: 

I'm using docsify-themeable, alongside with [docsify-sidebar-collapse](https://www.npmjs.com/package/docsify-sidebar-collapse) and it is currently working as expected, but the styles applied to the auto-generated `<li><a href>` itens are not applied to the simple `<li>` that I added in the `_sidebar.md`. And I can't use the dummy link `<a href="#">` inside docsify, because it will redirect to the homepage and cause the sidebar to malfunction.

My `_sidebar.md` looks like this:
```markdown
  - Section1 Toggle1
    - [Doc1.1](section1/doc1.1)
    - [Doc1.2](section1/doc1.2)
    - [Doc1.3](section1/doc1.3)
    - [Doc1.4](section1/doc1.4)
  - Section2 Toggle2
    - [Doc2.1](section1/doc2.1)
    - [Doc2.2](section1/doc2.2)
    - [Doc2.3](section1/doc2.3)
    - [Doc2.4](section1/doc2.4)
``` 
![Screenshot from 2020-07-16 11-20-38](https://user-images.githubusercontent.com/28402016/87682707-8cb4de80-c756-11ea-86db-b3ebe3981fc7.png)
![Screenshot from 2020-07-16 11-20-56](https://user-images.githubusercontent.com/28402016/87682721-8f173880-c756-11ea-959f-fb7767c1b886.png)

And if I use `- [Section1 Toggle1](#)`  the style is correctly applied, but then the toggle doesn't work

What I want is for it to look like this:
![Screenshot from 2020-07-16 11-27-33](https://user-images.githubusercontent.com/28402016/87683426-73f8f880-c757-11ea-8190-27736dcf7d9c.png)

Thanks in advance and I apologise again if this is a simple request, but I couldn't make it work

**Comment by jhildenbiddle** [comment]
Hi @ajmedeiros,

The easiest way to address your issue is to use the sidebar.css file linked in the [docsify-sidebar-collapse] docs. The arrow isn't an exact match for the one used by docsify-themeable, but it's very close.

If you want an exact match, you can add the following `<style>` tag to your `index.html` file:

```html
<style>
    :root {
        --sidebar-nav-pagelink-background-image: none;
        --sidebar-nav-link-before-content: '-';
    }

    .sidebar-nav ul > li.folder {
        background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='7' height='11.2' viewBox='0 0 7 11.2'%3E%3Cpath d='M1.5 1.5l4 4.1 -4 4.1' stroke-width='1.5' stroke='rgb%28179, 179, 179%29' fill='none' stroke-linecap='square' stroke-linejoin='miter' vector-effect='non-scaling-stroke'/%3E%3C/svg%3E");
        background-repeat: no-repeat;
        background-position: left calc(1em - 8px);
        padding-left: 16px;
    }

    .sidebar-nav ul > li.folder.open {
        background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='11.2' height='7' viewBox='0 0 11.2 7'%3E%3Cpath d='M1.5 1.5l4.1 4 4.1-4' stroke-width='1.5' stroke='rgb%2811, 135, 218%29' fill='none' stroke-linecap='square' stroke-linejoin='miter' vector-effect='non-scaling-stroke'/%3E%3C/svg%3E");
        background-position: left calc(1em - 6px);
    }

    .sidebar-nav li.folder > ul {
        margin-left: 0;
    }

    .sidebar-nav li.folder li.file > a {
        padding-left: 0;
    }
</style>
```

The final result will look like this:

<img width="167" alt="Screen Shot 2020-10-02 at 3 20 40 PM" src="https://user-images.githubusercontent.com/442527/94966484-fbd2e100-04c2-11eb-8eb7-448f99b344bf.png">

FWIW, the CSS selectors in the `<style>` block above are pretty silly. The selectors require a high [CSS specificity](https://css-tricks.com/specifics-on-css-specificity/) in order to override existing styles.
