### ISSUE TITLE
404 for .min.js.map files

### ISSUE THREAD

**Issue by Valtn** [jhildenbiddle/docsify-themeable#54]
While testing locally I noticed that some `.min.js.map` files were returning a 404 but I then realized that also happens on https://jhildenbiddle.github.io/docsify-themeable/#/

![image](https://user-images.githubusercontent.com/19395782/89595358-4ff27980-d822-11ea-8a4e-29c544988f40.png)
```
DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/docsify-themeable.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/docsify-tabs.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/docsify-copy-code.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

Locally I was just using docsify-themeable so changing:
```html
<script src="https://cdn.jsdelivr.net/npm/docsify-themeable@0"></script>
```
to:
```html
<script src="https://cdn.jsdelivr.net/npm/docsify-themeable@0/dist/js/docsify-themeable.min.js"></script>
```
fixed the issue for the `docsify-themeable.min.js.map` file.

I'm not sure if it is recommended to use that URL.

**Comment by jhildenbiddle** [comment]
Good call, @Valtn.

These 404 errors are harmless, but I agree it would be nice to not see them. I'll update the docs accordingly.

Thanks!
