### ISSUE TITLE
Support for  Docsify`hidesidebar` feature?

### ISSUE THREAD

**Issue by paulhibbitts** [jhildenbiddle/docsify-themeable#55]
Hello!

I am looking into embedding Docsify content into another platform, and came across the amazing new feature `hidesidebar`:
https://github.com/docsifyjs/docsify/pull/1026

While this works as expected with a standard Docsify theme I get this result when using Themable:
<img width="1200" alt="2020-08-17_16-36-14" src="https://user-images.githubusercontent.com/1812771/90455968-5bf4fb80-e0ac-11ea-8c3e-032f49889a65.png">

Is there any chance Themeable could also support `hidesidebar` and not still display the empty sidebar space?

Thanks very much,
Paul

**Comment by jhildenbiddle** [comment]
@paulhibbitts --

~~Just a heads up that I've created a separate PR in the docsify repo to adress this issue: https://github.com/docsifyjs/docsify/issues/1382.~~

Nevermind. Easy fix. :)

**Comment by paulhibbitts** [comment]
Hi @jhildenbiddle , sorry for the delayed response... some how I missed this one!

Thanks so much for considering this issue and the commit, but I am still seeing the space of the sidebar when I set `hidesidebar` to `true`:
https://paulhibbitts.github.io/test-docsify-open-course-starter-kit/#/

Is this intentional or am I doing something wrong with my config?
https://github.com/paulhibbitts/test-docsify-open-course-starter-kit/blob/master/docs/index.html

Thanks again for so kindly considering this issue!
Paul
ps - BTW, my main reason for the feature request is to enable the seamless embedding of single Docsify pages within other platforms etc.

**Comment by paulhibbitts** [comment]
Thanks so much @jhildenbiddle , and I just figured out that extra spacing on the left was due to a larger Browser window LOL!
