### ISSUE TITLE
Have both simple and simple dark theme and switch with button

### ISSUE THREAD

**Issue by AnLupoTamTamy** [jhildenbiddle/docsify-themeable#59]
I'm using the `Simple Theme`.

It would be possible to include both `Simple Theme` and `Simple Dark Theme` in my `index.html` and a switch button that allows the user to toggle between the two themes? For example with *Sun*/*Moon* icons, or a toggle button.

I don't have an idea on how to do it right now. 
A consideration could be save in a cookie the theme chosen.

Thank you in advance for any replies or explanations.

**Comment by CN-GuoZiyang** [comment]
+1 I want it too

**Comment by CN-GuoZiyang** [comment]
> I'm using the `Simple Theme`.
> 
> It would be possible to include both `Simple Theme` and `Simple Dark Theme` in my `index.html` and a switch button that allows the user to toggle between the two themes? For example with _Sun_/_Moon_ icons, or a toggle button.
> 
> I don't have an idea on how to do it right now.
> A consideration could be save in a cookie the theme chosen.
> 
> Thank you in advance for any replies or explanations.

I found something, https://docsify-darklight-theme.boopathikumar.me/#/, take a look

**Comment by AnLupoTamTamy** [comment]
That's exactly what I was looking for! It's also compatible by default with docsify-themeable : https://docsify-darklight-theme.boopathikumar.me/#/docsifyThemeable
Thank you!
