### ISSUE TITLE
How to automate workflow

### ISSUE THREAD

**Issue by aaronkjones** [jhildenbiddle/docsify-themeable#6]
First of all, thank you for the theme.

Repo in question: [noobs-term](https://github.com/aaronkjones/noobs-term)

I would like to automate the workflow. Currently, updating requires me to edit README.md in the root of the project folder and since I cannot reinitialize (something like `docsify init -t simple ./docs`) I have to manually edit <root>/docs/README.md as well. 

Keeping them in sync is becoming a chore. I am probably overlooking something very simple, but I would like the ability to automate this with docs init or something similar.

I will add it to my TODOs and research it, but I thought you may have an idea.

Thanks again.

**Comment by jhildenbiddle** [comment]
Hi @aaronkjones.

Here are two options:

1. Set your homepage to the hosted version of your repo's README.

   ```javascript
   window.$docsify = {
     homepage: 'https://raw.githubusercontent.com/aaronkjones/noobs-term/master/README.md'
     // ...
   };
   ```

   This will allow you to have one file providing documentation for both GitHub and your docsify site.

   If you want to preview a local copy of your site along with local README changes, you can set the homepage dynamically:

   ```javascript
   window.$docsify = {
     homepage:  window.location.hostname === 'localhost' ? '/README.md' : 'https://raw.githubusercontent.com/aaronkjones/noobs-term/master/README.md'
     // ...
   };
   ```

   Then launch a webserver **from the root of your repo** (not from the `/docs` directory):

   ```bash
   cd /path/to/repo
   http-server
   ```

   Now when you visit http://localhost:8080/docs/ you will see your docsify site with `/README.md` set as the homepage. When viewing https://noobs-term.com, the homepage will be set to `https://raw.githubusercontent.com/aaronkjones/noobs-term/master/README.md`. 

1. Provide full documentation via the website only (`/docs`)

   Use the repo README to provide summary information only and direct viewers to the website. This is the option I chose for projects like [docsify-themeable](https://github.com/jhildenbiddle/docsify-themeable) and [docsify-tabs](https://github.com/jhildenbiddle/docsify-tabs). There's some duplication (badges, description, contact, license, etc.), but that's content that doesn't change very often. 

   If you go this route, just be sure to keep a description in the repo README and in a `<meta name="description" content="...">` tag in your `index.html` for SEO purposes.

Hope this helps, and glad you are enjoying the theme!

**Comment by aaronkjones** [comment]
Thank you @jhildenbiddle for the quick feedback. Option 2 certainly seems more straight-forward. I will give them both a run through and see how it goes.
