### ISSUE TITLE
possible bug: clicking a bit outside '.clear-button' element won't unhide `.sidebar-nav`

### ISSUE THREAD

**Issue by rizdaprasetya** [jhildenbiddle/docsify-themeable#62]
Hi, awesome and useful plugin! Love it!
I found this possible bug during the use of this plugin:

### When
- I visit https://jhildenbiddle.github.io/docsify-themeable/#/
- then enter any string into `search bar`
- then click a bit outside (under/above) the `.clear-button` element (highlighted red in below screenshot)
> <img width="615" alt="Screen Shot 2021-02-15 at 11 57 49" src="https://user-images.githubusercontent.com/13027142/107907364-198e7780-6f86-11eb-95b9-ceff7fea5b94.png">
- then search bar is properly cleared, but

### Unexpected Case
- It somehow **won't unhide** (restore visibility of) `.sidebar-nav`, leaving the sidebar navigation empty (even though there is no active search results)
> 
<img width="575" alt="Screen Shot 2021-02-15 at 11 57 58" src="https://user-images.githubusercontent.com/13027142/107907628-c2d56d80-6f86-11eb-8e5f-df6080be5999.png">

### Expected Case
- It should unhide (restore visibility of) `.sidebar-nav`

The issue doesn't occur if you click right at the `.clear-button`. Though.

I haven't able to dig deeper on what potentially goes wrong technically, but anyway submitting this bug to document it.

Cheers.

**Comment by jhildenbiddle** [comment]
Hi @rizdaprasetya.

~~I've made the fix on the [dev](https://github.com/jhildenbiddle/docsify-themeable/tree/dev) branch. Feel free to check it out, build, and give the new CSS a try. If all goes well I'll push an update to npm.~~

Fixed in 0.8.5
