### ISSUE TITLE
cannot change '>' and 'v' color

### ISSUE THREAD

**Issue by lebonez** [jhildenbiddle/docsify-themeable#65]
I am working on a theme and I cannot change '>' and 'v' color for the life of me. I've searched and searched. I'm using the simple theme. Below it is squared in red. My goal is to make it roughly match the base or theme color which isn't set in the photo at the moment. I've tried all of the sidebare before content.
![image](https://user-images.githubusercontent.com/25910791/123546951-5e8c9c80-d724-11eb-8154-0bb8a94df0c0.png)

**Comment by jhildenbiddle** [comment]
See #3 and #58.

**Comment by jhildenbiddle** [comment]
Fixed in v0.9.0
