### ISSUE TITLE
The drop-down arrow does not appear when using "routerMode: 'history'"

### ISSUE THREAD

**Issue by utybo** [jhildenbiddle/docsify-themeable#66]
When using `routerMode: history` in Docsify's configuration, the links that would normally look like `my.docs.example.org/#/SomePage` are turned into `my.docs.example.org/SomePage`. The `<a>` href themselves are turned from `#/SomePager` to `/SomePage`. Unfortunately, this causes the drop-down arrow to stop appearing on same-site links due to [this line](https://github.com/jhildenbiddle/docsify-themeable/blob/7008137b8079bc267e66e653dedb18d8e417f605/src/scss/app/_sidebar.scss#L216) which restricts such arrows to links that begin with `#/`.

Without `routerMode: 'history'`:

![image](https://user-images.githubusercontent.com/5175705/131525214-fb9495d2-fcfb-4578-949c-0e4c853947a5.png)

With `routerMode: 'history'`:

![image](https://user-images.githubusercontent.com/5175705/131525366-da111a49-3464-4983-9dfd-8c5f0a32f8b9.png)

Manually editing a link via the dev tools to add a `#/` at the beginning restores the arrow (but breaks the link).

I do not really know how this could be fixed, maybe loosening the restriction to `/` or `#/` and not just `#/`?

**Comment by jhildenbiddle** [comment]
Hi @utybo.

~~I've made the fix on the [dev](https://github.com/jhildenbiddle/docsify-themeable/tree/dev) branch. Feel free to check it out, build, and give the new CSS a try. If all goes well I'll push an update to npm.~~

Fixed in 0.8.5

**Comment by utybo** [comment]
Thanks! I tested it on my side, works perfectly fine! Thank you very much for the quick fix!
