### ISSUE TITLE
Changing the padding (top/bottom) on "blockquote"

### ISSUE THREAD

**Issue by DiasFranciscoA** [jhildenbiddle/docsify-themeable#67]
Don't know if this is possible I've been dueling to find it in the docs... but don't know if I'm missing something.
Could someone point me in the right direction?

**Comment by trusktr** [comment]
If you don't see an option for it, you may just have to inspect elements and see what selector you can use to apply the styling.

**Comment by jhildenbiddle** [comment]
@DiasFranciscoA --

A new custom property will be available in the next release: `--blockquote-padding`:

```html
<style>
:root {
  --blockquote-padding: 1.5em; /* Default */
}
</style>
```

The update will be published before EOD tomorrow.
