### ISSUE TITLE
table alignment doesn't take effect

### ISSUE THREAD

**Issue by abelsu7** [jhildenbiddle/docsify-themeable#7]
![](https://qiniu.abelsu7.cn/notes-2018118-table-align.png)

The screenshot is taken from [here](https://jhildenbiddle.github.io/docsify-themeable/#/markdown?id=tables). 

Both Opera `56.0.3051.52` and Chrome `69.0.3497.92` on Windows 10 find this problem.

**Comment by jhildenbiddle** [comment]
Fixed in 0.5.1

Thanks, @abelsu7.
