### ISSUE TITLE
Sidebar not aligning to left of page

### ISSUE THREAD

**Issue by Yorams** [jhildenbiddle/docsify-themeable#70]
I applied the quickstart installation instructions to a new initiated docsify instance. But the sidebar is not aligned to the left as you can see on the screenshot:
![image](https://user-images.githubusercontent.com/13483484/148511312-5c9b7685-4e29-4f0a-a58d-a0ca614e79c1.png)

In my HTML document are only some basic settings and not something theme or styling related. It also happens on a clean "docsify init" document.

**Comment by jhildenbiddle** [comment]
@Yorams --

You are most likely loading two conflicting themes: the one used by `docsify-cli` and the one you added for docsify-themeable. 

Just remove the following line from your `index.html`:

```html
<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/docsify@4/lib/themes/vue.css">
```
