### ISSUE TITLE
sidebar not aligned between file and folder classes

### ISSUE THREAD

**Issue by DanielYWoo** [jhildenbiddle/docsify-themeable#71]
#### Steps to reproduce
create a sidebar
```
* Whatever
  * [Home](/)
* User Guides
  * [Setup Development Environment](/_user-guide/setup/)  
```
It works perfectly. Now change it to
```
* [Home](/)
* User Guides
  * [Setup Development Environment](/_user-guide/setup/)  
  * [Microservice with REST APIs is dead simple](/_user-guide/platform-lightweight-rest/)
```
The Overview has a different class and cannot be displayed correctly.
![image](https://user-images.githubusercontent.com/514417/155501072-f297a9ab-e801-4f0b-a890-0d1ca24bf708.png)

This is because the class is different:
![image](https://user-images.githubusercontent.com/514417/155501271-dd8528a9-6fcc-4dff-9747-e6e606e4836d.png)

## reproducible sandbox 
[code sandbox demo](https://codesandbox.io/embed/dreamy-nobel-3qyr81?fontsize=14&hidenavigation=1&theme=dark)

**Comment by DanielYWoo** [comment]
anybody has an idea how to workaround this?

**Comment by jhildenbiddle** [comment]
This appears to be an issue with the [docsify-sidebar-collapse](https://github.com/iPeng6/docsify-sidebar-collapse) which you are using in your demo. Docsify-themeable cannot adjust its default styles to accommodate individual plugins. Your best option is to contact the plugin author and ask them to explore making their plugin compatible with docsify-themeable.
