### ISSUE TITLE
Page content is not using all available space on large screens

### ISSUE THREAD

**Issue by vellala2000** [jhildenbiddle/docsify-themeable#74]
noticed page content is not using the entire space available especially on large monitors. It would be great if we can adjust to use all available space.

![image](https://user-images.githubusercontent.com/3084986/172918370-f5540eba-944a-49f7-9581-4d557c60896a.png)

**Comment by jhildenbiddle** [comment]
Hi @vellala2000 --

You can control the `max-width` of the content area using the `--content-max-width` custom property:

```html
<style>
:root {
  --content-max-width: none;
}
</style>
```

See the [Customization](https://jhildenbiddle.github.io/docsify-themeable/#/customization) portion of the documentation for details.
