### ISSUE TITLE
On a phone brower, when touching any sidebar contents, the sidebar will hide automatically.

### ISSUE THREAD

**Issue by pbjacob** [jhildenbiddle/docsify-themeable#77]
As said in title.
This is not convenient when my desired document is under sub-folders. I have to activate the sidebar again and again, because it hides again and again whenever I select the next sub-folder. This happens only on a sell phone web browser (as far as I test, Safari).

The original docsify themes are not like this. The sidebar will stay on the screen until you touch the document content aera.

So can this be improved or add an option to choose the behavior of the sidebar on sell phone?
Thank you so much.

**Comment by jhildenbiddle** [comment]
Hi @pbjacob --

Can you provide a link to a docsify site that demonstrates the sidebar behavior you are referring to? If possible, an example with a public repo available for review would be best.

The reason I ask is because I am not able to reproduce the behavior you are describing with docsify's default themes.

**Comment by pbjacob** [comment]
Thanks for replying.
Here is the link of my personal PAGE: http://njupt_zbo.gitee.io/my-public-wiki/#/
All the items shown in the sidebar are actually folders, not docs. When you touch any folder, or subfolder on iPhone Safari, the sidebar will hide. 
Actually, this happens the same way on your HomePage(https://jhildenbiddle.github.io/docsify-themeable/#/introduction), except that all the items in your sidebar are docs, not folders. But I still think it is better not hiding the sidebar automatically when touching any sidebar doc name, because there are situations that I wanna continiously choose a subsection right in the sidebar, not having to swap it back again to choose.

Thank you so much again.

**Comment by pbjacob** [comment]
> Hi @pbjacob --
> 
> Can you provide a link to a docsify site that demonstrates the sidebar behavior you are referring to? If possible, an example with a public repo available for review would be best.
> 
> The reason I ask is because I am not able to reproduce the behavior you are describing with docsify's default themes.

I have switch the theme of my PAGES into docsify default dark theme. The link is the same one with the last post : http://njupt_zbo.gitee.io/my-public-wiki/#/

You can open the website on a phone browser and try to expand CadQuery folder to see. The sidebar won't hide until you touch the article content on the right or touch the little TOC icon at the down-left corner.

**Comment by jhildenbiddle** [comment]
The expand/collapse functionality is not native docsify behavior. You are using a plugin names [docsify-plugin-collapse](https://github.com/iPeng6/docsify-sidebar-collapse) which is apparently compatible with the default themes provided by docisfy but not docsify-themeable. I am not familiar with this plugin, so my recommendation is to create an issue in that repo and see if the plugin's author can offer assistance.

**Comment by pbjacob** [comment]
Thanks for your replay any way.
