### ISSUE TITLE
Switch button for dark/light mode

### ISSUE THREAD

**Issue by chnuessli** [jhildenbiddle/docsify-themeable#81]
Can we add a switch button for dark/light mode? For example, i have system standard "dark" but i want to read at the moment in light mode. Easy switch button would please me very fast. Also, it made your beautiful themes more modern.

**Comment by userdocs** [comment]
This project can do it and has support for themeable

https://docsify-darklight-theme.boopathikumar.me/#/docsifyThemeable

**Comment by chnuessli** [comment]
Thanks @userdocs this is what i was searching for :)
